#!/usr/bin/env bash

cd /root

cat <<EOF
***********************************
Welcome to the PyPI auth container!
You can use htpasswd to modify /root/auth/htpasswd.
/root/auth will be mounted readonly in the PyPI container.

To create an auth/htpasswd file,

~$ [ ! -f auth/htpasswd ] && htpasswd -c -B auth/htpasswd <username>

To add a user to an existing auth/htpasswd,

~$ htpasswd auth/htpasswd <username>

This is bash, and you are in $(pwd).
EOF

bash
